name: Debug PRRC Connector

on:
  workflow_dispatch: # run manually from Actions tab

jobs:
  debug-rics-token:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install requests

      - name: Diagnose RICS Token
        env:
          RICS_API_TOKEN: ${{ secrets.RICS_API_TOKEN }}
        run: python scripts/diagnose_rics_token.py

  debug-meta-events:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install requests

      - name: Test Meta Offline Events
        env:
          META_ACCESS_TOKEN: ${{ secrets.META_ACCESS_TOKEN }}
          META_DATASET_ID: ${{ secrets.META_OFFLINE_EVENT_SET_ID }}
          TEST_EMAIL: ${{ secrets.TEST_EMAIL }}
        run: python scripts/test_meta_offline_events.py

  debug-full-sync:
    runs-on: ubuntu-latest
    needs: [debug-rics-token, debug-meta-events]
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run RICS sync with debug counters
        env:
          RICS_API_TOKEN: ${{ secrets.RICS_API_TOKEN }}
          GDRIVE_CREDENTIALS: ${{ secrets.GDRIVE_CREDENTIALS }}
          GDRIVE_FOLDER_ID_RICS: ${{ secrets.GDRIVE_FOLDER_ID_RICS }}
        run: python scripts/sync_rics_live.py --debug

      - name: Run RICS sync without dedup
        env:
          RICS_API_TOKEN: ${{ secrets.RICS_API_TOKEN }}
          GDRIVE_CREDENTIALS: ${{ secrets.GDRIVE_CREDENTIALS }}
          GDRIVE_FOLDER_ID_RICS: ${{ secrets.GDRIVE_FOLDER_ID_RICS }}
        run: python scripts/sync_rics_live.py --no-dedup --debug

      - name: Upload debug logs
        uses: actions/upload-artifact@v3
        with:
          name: debug-logs
          path: |
            logs/
            optimizely_connector/output/
