# .github/workflows/rics_to_meta.yml

on:
  workflow_dispatch:

jobs:
  rics-to-meta:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install google-api-python-client google-auth

      - name: Ensure data directory
        run: mkdir -p data

      - name: Configure Google creds
        env:
          GDRIVE_SA_KEY: ${{ secrets.GDRIVE_SA_KEY }}
        run: |
          echo "$GDRIVE_SA_KEY" | base64 --decode > sa.json
          export GOOGLE_APPLICATION_CREDENTIALS=sa.json

      - name: Download latest RICS export
        env:
          GDRIVE_FOLDER_ID_RICS: ${{ secrets.GDRIVE_FOLDER_ID_RICS }}
        run: python scripts/download_rics.py

      - name: Run Meta upload
        env:
          META_OFFLINE_SET_ID: ${{ secrets.META_OFFLINE_SET_ID }}
          META_OFFLINE_TOKEN:  ${{ secrets.META_OFFLINE_TOKEN }}
          RICS_CSV_PATH:       data/rics.csv
        run: python scripts/sync_rics_to_meta.py
