# .github/workflows/rics_to_meta.yml

# Trigger manually or on a daily schedule at 8:00 UTC
on:
  workflow_dispatch:
  schedule:
    - cron: '0 8 * * *'

jobs:
  rics-to-meta:
    name: Sync RICS → Meta Offline Events
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Pull RICS CSV
        # Replace this with your existing step that produces data/rics.csv
        run: echo "Assume data/rics.csv is present"

      - name: Run Meta upload
        env:
          META_OFFLINE_SET_ID: ${{ secrets.META_OFFLINE_SET_ID }}
          META_OFFLINE_TOKEN:   ${{ secrets.META_OFFLINE_TOKEN }}
          RICS_CSV_PATH:        data/rics.csv
        run: |
          set -e
          python scripts/sync_rics_to_meta.py
