name: Run RunSignUp connector

on:
  workflow_dispatch:
  schedule:
    - cron: '0 8 * * *'  # Runs daily at 3:00 AM EST / 8:00 AM UTC

jobs:
  run-signup:
    runs-on: ubuntu-latest

    env:
      RUNSIGNUP_API_KEY: ${{ secrets.RUNSIGNUP_API_KEY }}
      RUNSIGNUP_API_SECRET: ${{ secrets.RUNSIGNUP_API_SECRET }}
      RUNSIGNUP_PARTNER_IDS: ${{ secrets.RUNSIGNUP_PARTNER_IDS }}
      GDRIVE_FOLDER_ID_1384: ${{ secrets.GDRIVE_FOLDER_ID_1384 }}
      GDRIVE_FOLDER_ID_1385: ${{ secrets.GDRIVE_FOLDER_ID_1385 }}
      GDRIVE_FOLDER_ID_1411: ${{ secrets.GDRIVE_FOLDER_ID_1411 }}
      GDRIVE_FOLDER_ID_RICS: ${{ secrets.GDRIVE_FOLDER_ID_RICS }}
      OPTIMIZELY_API_TOKEN: ${{ secrets.OPTIMIZELY_API_TOKEN }}

    steps:
      - name: ⬇️ Checkout repository
        uses: actions/checkout@v3

      - name: 🐍 Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: 📦 Install dependencies
        run: |
          pip install -r requirements.txt

      - name: 🚀 Run RunSignUp connector
        run: python runsignup_connector/main_runsignup.py
